import { SurveySection } from '../types';
import {
  ENTREGA_TIEMPO,
  MONEDAS,
  SI_NO_COD,
  SI_NO_NA,
  eq,
  evidenciasModule,
} from './constants';
import { usdFrom } from './computed';

// Parte 3 — cuestionario 03.08 (E + F). IDs internos estables.
// Desviación de fecha eliminada (no figura desde Word 31.07).

export const parte3: SurveySection = {
  id: 'parte-3',
  title: 'Parte 3 — Entrega',
  description: 'Cancelaciones, recepción del paquete, transportadora y documentación.',
  modules: [
    {
      id: 'compras-no-entregadas',
      title: 'COMPRAS NO ENTREGADAS O CANCELADAS',
      questions: [
        {
          id: 'q-cn-entregada',
          codigoOriginal: 'E01',
          text: 'E01. ¿La compra fue entregada?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q-cn-informado-cancelacion',
          codigoOriginal: 'E02',
          text: 'E02. ¿Fue informado que la compra fue cancelada?',
          type: 'single',
          options: SI_NO_COD,
          showIf: eq('q-cn-entregada', '2'),
          required: true,
        },
        {
          id: 'q-cn-fecha-cancelacion',
          codigoOriginal: 'E02.1',
          text: 'E02.1. ¿Cuál fue la fecha de cancelación de la compra?',
          type: 'date',
          showIf: eq('q-cn-informado-cancelacion', '1'),
          required: true,
        },
        {
          id: 'q-cn-motivo',
          codigoOriginal: 'E02.2',
          text: 'E02.2. ¿Cuál fue el motivo de cancelación que le informaron?',
          type: 'text',
          showIf: eq('q-cn-entregada', '2'),
          required: true,
        },
        {
          id: 'q-cn-reembolso-dias',
          codigoOriginal: 'E03',
          // Word: E02=1 y reembolso acreditado — lo segundo no es codificable
          text: 'E03. ¿Cuántos días naturales transcurren entre la cancelación y la acreditación del reembolso?',
          type: 'number',
          showIf: eq('q-cn-informado-cancelacion', '1'),
          required: true,
        },
      ],
    },
    {
      id: 'entrega',
      title: 'ENTREGA',
      questions: [
        {
          id: 'q32-fecha-recepcion',
          codigoOriginal: 'F01',
          text: 'F01. ¿En qué fecha recibió finalmente el producto?',
          type: 'date',
          required: true,
        },
        {
          id: 'q33-hora-recepcion',
          codigoOriginal: 'F02',
          text: 'F02. ¿A qué hora recibió el producto?',
          type: 'time',
          required: true,
        },
        {
          id: 'q33a-foto-recepcion',
          codigoOriginal: 'F02.1',
          text: 'F02.1. Adjunte una evidencia de la fecha y hora de recepción del producto.',
          type: 'evidence',
          required: false,
        },
        {
          id: 'q34-entrega-tiempo',
          codigoOriginal: 'F03',
          text: 'F03. En relación con la promesa original, ¿cuándo se entrega el producto?',
          type: 'single',
          options: ENTREGA_TIEMPO,
          required: true,
          hint: 'Si el producto tarda 10 días más que su promesa de entrega, dar el caso por cerrado y seleccionar la respuesta "Nunca llegó”',
        },
        {
          id: 'q35-notif-entrega',
          codigoOriginal: 'F04',
          text: 'F04. ¿Recibió una notificación que confirma la entrega del producto?',
          type: 'single',
          options: SI_NO_NA,
          required: true,
        },
        {
          id: 'q36-comunicacion-retraso',
          codigoOriginal: 'F05',
          text: 'F05. En caso de retraso/delay, ¿Recibió alguna comunicación indicando cuál sería la nueva previsión de entrega?',
          type: 'single',
          options: SI_NO_NA,
          showIf: eq('q34-entrega-tiempo', '1'),
          required: true,
        },
        {
          id: 'q36a-nueva-fecha',
          codigoOriginal: 'F05.1',
          text: 'F05.1. ¿Cuál es la nueva fecha estimada de entrega?',
          type: 'date',
          showIf: eq('q36-comunicacion-retraso', '1'),
          required: true,
        },
        {
          id: 'q36b-compensacion-demora',
          codigoOriginal: 'F06',
          text: 'F06. ¿Recibió alguna compensación por la demora?',
          type: 'single',
          options: SI_NO_NA,
          showIf: eq('q34-entrega-tiempo', '1'),
          required: true,
        },
        {
          id: 'q36c-cual-compensacion',
          codigoOriginal: 'F06.1',
          text: 'F06.1. ¿Cuál es la compensación?',
          type: 'text',
          showIf: eq('q36b-compensacion-demora', '1'),
          required: true,
        },
        {
          id: 'q35-dias-llegada',
          codigoOriginal: 'F07',
          text: 'F07. ¿Cuántos días naturales transcurren desde la fecha de compra hasta la entrega del producto?',
          type: 'number',
          required: true,
        },
        {
          id: 'q36-llego-segun-anuncio',
          codigoOriginal: 'F08',
          text: 'F08. ¿El producto recibido coincide con la descripción y las condiciones informadas en la publicación?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q38-q1-22-transportadora',
          codigoOriginal: 'F09',
          text: 'F09. ¿Con qué transportadora se envió el paquete?',
          type: 'text',
          required: true,
          hint: 'La transportadora es quien realizó el transporte de la compra. La indicación de la transportadora suele ser indicada en el paquete o recibo. Si el paquete/recibo no indica, indique "No se especifica".\n*No confundir a quien Envía el producto con la Transportadora. Quien Envía el producto (pregunta "A12. Enviado por") es siempre el marketplace evaluado. La Transportadora es quien realiza el traslado del paquete hacia su destino (puede ser el mismo marketplace, o bien una empresa terciarizada, o bien no identificarse).',
        },
        {
          id: 'q38-q1-22a-nac',
          codigoOriginal: 'F09.1',
          text: 'F09.1. ¿Con qué transportadora nacional se envió el paquete?',
          type: 'text',
          required: true,
          hint: 'La indicación de la transportadora suele ser indicada en el paquete o recibo. Si el paquete/recibo no indica, indique "No se especifica".',
        },
        {
          id: 'q38-q1-22b-int',
          codigoOriginal: 'F09.2',
          text: 'F09.2. ¿Con qué transportadora internacional se envió el paquete?',
          type: 'text',
          required: true,
          hint: 'La indicación de la transportadora suele ser indicada en el paquete o recibo. Si el paquete/recibo no indica, indique "No se especifica".',
        },
        {
          id: 'q40-paquete-estado',
          codigoOriginal: 'F10',
          text: 'F10. ¿El paquete exterior llegó en buen estado?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q41-foto-etiqueta',
          codigoOriginal: 'F10.1',
          text: 'F10.1. Adjunte una foto de la etiqueta del paquete.',
          type: 'evidence',
          required: false,
        },
        {
          id: 'q41a-foto-antes',
          codigoOriginal: 'F10.2',
          text: 'F10.2. Adjunte una foto del paquete antes de abrirlo.',
          type: 'evidence',
          required: false,
        },
        {
          id: 'q39-producto-estado',
          codigoOriginal: 'F11',
          text: 'F11. ¿El producto llegó en buen estado?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q42-foto-despues',
          codigoOriginal: 'F11.1',
          text: 'F11.1. Adjunte una foto del producto después de desembalarlo.',
          type: 'evidence',
          required: false,
        },
        {
          id: 'q46-nfe',
          codigoOriginal: 'F12',
          text: 'F12. ¿Recibió un comprobante fiscal de la compra?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
          hint: 'El comprobante fiscal contiene los datos fiscales del vendedor y la descripción del producto comprado. Puede recibirse en formato digital o físico.',
        },
        {
          id: 'q46a-foto-nfe',
          codigoOriginal: 'F12.1',
          text: 'F12.1. Adjunte una foto o captura del comprobante fiscal.',
          type: 'evidence',
          showIf: eq('q46-nfe', '1'),
          required: false,
        },
        {
          id: 'q46b-valor-nfe',
          codigoOriginal: 'F12.2',
          // Typo del Word ("ene l") — fidelidad literal
          text: 'F12.2. ¿El valor del producto indicado en el comprobante fiscal coincide con el precio del producto ene l marketplace?',
          type: 'single',
          options: SI_NO_COD,
          showIf: eq('q46-nfe', '1'),
          required: true,
        },
        {
          id: 'q46c-precio-final',
          codigoOriginal: 'F13',
          text: 'F13. ¿Cuál es el importe final total de la compra, incluyendo producto, envío, impuestos y otros cargos?',
          type: 'number',
          required: true,
        },
        {
          id: 'q46c-1-moneda',
          codigoOriginal: 'F13.1',
          text: 'F13.1. ¿En qué moneda está expresado el importe final total de la compra?',
          type: 'single',
          options: MONEDAS,
          required: true,
        },
        {
          id: 'q46c-2-precio-usd',
          codigoOriginal: 'F13.2',
          text: 'F13.2. Importe final total de la compra en dólares. VARIABLE AUXILIAR AUTOMÁTICA.',
          type: 'number',
          required: false,
          computed: usdFrom('q46c-precio-final', 'q46c-1-moneda'),
        },
      ],
    },
    evidenciasModule(3),
  ],
};
