import { SurveySection } from '../types';
import {
  ENTREGA_TIEMPO,
  MONEDAS,
  SI_NO_COD,
  SI_NO_NA,
  TRANSPORTADORAS_INT,
  TRANSPORTADORAS_NAC,
  eq,
  evidenciasModule,
} from './constants';
import { naturalDaysBetween, usdFrom } from './computed';

// Parte 3: entrega
// Textos literales del .docx (fidelidad textual). P70–P72 fuera.

export const parte3: SurveySection = {
  id: 'parte-3',
  title: 'Parte 3 — Entrega',
  description: 'Recepción del paquete, transportadora y documentación.',
  modules: [
    {
      id: 'entrega',
      title: 'ENTREGA',
      questions: [
        {
          id: 'q33-fecha-recepcion',
          codigoOriginal: '33',
          text: '33. ¿Cuál es la fecha final de recepción del producto?',
          type: 'datetime',
          required: true,
        },
        {
          id: 'q33a-foto-recepcion',
          codigoOriginal: '33a',
          text: '33a. Adjuntar foto de la fecha final y hora de recepción del producto',
          type: 'evidence',
          required: false,
        },
        {
          id: 'q32-entrega-tiempo',
          codigoOriginal: '32',
          text: '32. ¿El producto se entregó a tiempo?',
          type: 'single',
          options: ENTREGA_TIEMPO,
          required: true,
          hint: 'Si el producto tarda 10 días más que su promesa de entrega, dar el caso por cerrado y seleccionar la respuesta "Nunca llegó”',
        },
        {
          id: 'q32q4-notif-entrega',
          codigoOriginal: '32Q4.23.a',
          text: '32Q4.23.a ¿Recibió una notificación por la entrega del producto?',
          type: 'single',
          options: SI_NO_NA,
          required: true,
        },
        {
          id: 'q32b-comunicacion-retraso',
          codigoOriginal: '32b',
          text: '32b. En caso de retraso/delay, ¿Recibiste alguna comunicación indicando cuál sería la nueva previsión de entrega?',
          type: 'single',
          options: SI_NO_NA,
          required: true,
        },
        {
          id: 'q32c-nueva-fecha',
          codigoOriginal: '32c',
          text: '32c. ¿Cuál era la nueva fecha prevista?',
          type: 'date',
          showIf: eq('q32b-comunicacion-retraso', '1'),
          required: true,
        },
        {
          id: 'q32d-compensacion-demora',
          codigoOriginal: '32d',
          text: '32d. En caso de retraso/delay, ¿recibiste alguna compensación por la demora?',
          type: 'single',
          options: SI_NO_NA,
          required: true,
        },
        {
          id: 'q32e-cual-compensacion',
          codigoOriginal: '32e',
          text: '32e. ¿Cuál fue la compensación?',
          type: 'text',
          showIf: eq('q32d-compensacion-demora', '1'),
          required: true,
        },
        {
          id: 'q35-dias-llegada',
          codigoOriginal: '35',
          text: '35. ¿A cuántos días naturales de la fecha de compra llegó el producto?',
          type: 'number',
          required: false,
          computed: naturalDaysBetween('q01-fecha-compra', 'q33-fecha-recepcion'),
        },
        {
          id: 'q38-llego-segun-anuncio',
          codigoOriginal: '38',
          text: '38. ¿Llegó el producto según lo informado en el anuncio del sitio web?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q38-q1-22-transportadora',
          codigoOriginal: '38.Q1.22',
          text: '38.Q1.22. ¿Con qué transportadora se envió el paquete?',
          type: 'text',
          required: true,
          hint: 'La transportadora es quien realizó el transporte de la compra. La indicación de la transportadora suele ser indicada en el paquete o recibo. Si el paquete/recibo no indica, favor indicar "no especifica".',
        },
        {
          id: 'q38-q1-22a-nac',
          codigoOriginal: '38.Q1.22.a',
          text: '38.Q1.22.a. ¿Con qué transportadora nacional se envió el paquete?',
          type: 'single',
          options: TRANSPORTADORAS_NAC,
          required: true,
          hint: 'La indicación de la transportadora suele ser indicada en el paquete o recibo. Si el paquete/recibo no indica, favor indicar "no especifica".',
        },
        {
          id: 'q38-q1-22a-nac-otro',
          codigoOriginal: '38.Q1.22.a-otro',
          text: '38.Q1.22.a. Especifique transportadora nacional',
          type: 'text',
          showIf: eq('q38-q1-22a-nac', '97'),
          required: true,
        },
        {
          id: 'q38-q1-22b-int',
          codigoOriginal: '38.Q1.22.b',
          text: '38.Q1.22.b. ¿Con qué transportadora internacional se envió el paquete?',
          type: 'single',
          options: TRANSPORTADORAS_INT,
          required: true,
          hint: 'La indicación de la transportadora suele ser indicada en el paquete o recibo. Si el paquete/recibo no indica, favor indicar "no especifica".',
        },
        {
          id: 'q38-q1-22b-int-otro',
          codigoOriginal: '38.Q1.22.b-otro',
          text: '38.Q1.22.b. Especifique transportadora internacional',
          type: 'text',
          showIf: eq('q38-q1-22b-int', '97'),
          required: true,
        },
        {
          id: 'q40-paquete-estado',
          codigoOriginal: '40',
          text: '40. ¿El paquete estaba en buen estado?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q41-foto-etiqueta',
          codigoOriginal: '41',
          text: '41. Adjunte imagen de la etiqueta.',
          type: 'evidence',
          required: false,
        },
        {
          id: 'q41a-foto-antes',
          codigoOriginal: '41a',
          text: '41a. Adjunte la foto del pedido antes de abrirlo.',
          type: 'evidence',
          required: false,
        },
        {
          id: 'q39-producto-estado',
          codigoOriginal: '39',
          text: '39. ¿El producto estaba en buen estado?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q42-foto-despues',
          codigoOriginal: '42',
          text: '42. Adjunte la foto del producto después de desembalarlo.',
          type: 'evidence',
          required: false,
        },
        {
          id: 'q46-nfe',
          codigoOriginal: '46',
          text: '46. ¿Recibió Nota Fiscal Electrónica?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
          hint: 'La Nota, recibo o factura fiscal contiene los datos fiscales del vendedor y descripción del producto comprado. Este documento puede ser recibido por vía digital o física.',
        },
        {
          id: 'q46a-foto-nfe',
          codigoOriginal: '46a',
          text: '46a. Adjunte la foto de la Nota Fiscal Electrónica (NFE).',
          type: 'evidence',
          showIf: eq('q46-nfe', '1'),
          required: false,
        },
        {
          id: 'q46b-valor-nfe',
          codigoOriginal: '46b',
          text: '46b. ¿El valor del producto de la NFE es el mismo que el valor del producto en el site?',
          type: 'single',
          options: SI_NO_COD,
          showIf: eq('q46-nfe', '1'),
          required: true,
        },
        {
          id: 'q46c-precio-final',
          codigoOriginal: '46c',
          text: '46c. ¿Cuál es el precio final total de la compra (producto + envío + impuestos, etc)?',
          type: 'number',
          required: true,
        },
        {
          id: 'q46c-1-moneda',
          codigoOriginal: '46c.1',
          text: '46c.1. Moneda del precio final total de la compra (producto + envío + impuestos, etc).',
          type: 'single',
          options: MONEDAS,
          required: true,
        },
        {
          id: 'q46c-2-precio-usd',
          codigoOriginal: '46c.2',
          text: '46c.2. Precio final total en dólares de la compra (producto + envío + impuestos, etc). VARIABLE AUXILIAR AUTÓMATICA.',
          type: 'number',
          required: false,
          computed: usdFrom('q46c-precio-final', 'q46c-1-moneda'),
        },
        // TODO MELI: ENTREGA Total / CONTACTOS Total / Total (porcentaje) — sin fórmula
        // TODO MELI: Tipo de entrega (On time / Early) — sin criterio
        // TODO MELI: OK / NOT OK — sin criterio
        {
          id: 'q-desviacion-entrega',
          codigoOriginal: 'Desviación de la fecha de entrega',
          text: 'Desviación de la fecha de entrega -Días Naturales.',
          type: 'number',
          required: false,
          // Usa fecha exacta prometida cuando aplica; si fue intervalo, Ops/MELI deben definir criterio
          computed: naturalDaysBetween('q25a-fecha-prevista', 'q33-fecha-recepcion'),
        },
      ],
    },
    evidenciasModule(3),
  ],
};
