import { SurveySection } from '../types';
import {
  MEDIOS_NOTIFICACION,
  SI_NO_COD,
  SI_NO_NA,
  and,
  eq,
  evidenciasModule,
  range,
} from './constants';

// Parte 2 — cuestionario 03.08 (C + D). IDs internos estables.

export const parte2: SurveySection = {
  id: 'parte-2',
  title: 'Parte 2 — Notificaciones y contactos',
  description: 'Notificaciones del pedido y contacto con atención al cliente.',
  modules: [
    {
      id: 'notificaciones',
      title: 'NOTIFICACIONES',
      questions: [
        {
          id: 'q27-confirmacion',
          codigoOriginal: 'C01',
          text: 'C01. ¿Recibió una confirmación del pedido después de realizar la compra?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q27a-medio',
          codigoOriginal: 'C01.1',
          text: 'C01.1. ¿Por qué medio/s recibió la notificación?',
          type: 'multiple',
          options: MEDIOS_NOTIFICACION,
          showIf: eq('q27-confirmacion', '1'),
          required: true,
        },
        {
          id: 'q27a-medio-otro',
          codigoOriginal: 'C01.1-otro',
          text: 'C01.1. ¿Cuál otro medio?',
          type: 'text',
          showIf: eq('q27a-medio', '97'),
          required: true,
        },
        {
          id: 'q27b-foto-medio',
          codigoOriginal: 'C01.2',
          text: 'C01.2. Adjunte una captura del mensaje de confirmación del pedido.',
          type: 'evidence',
          showIf: eq('q27-confirmacion', '1'),
          required: true,
        },
        {
          id: 'q28-preparacion',
          codigoOriginal: 'C02',
          text: 'C02. ¿Recibió una notificación indicando que el pedido está en preparación?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q28a-medio',
          codigoOriginal: 'C02.1',
          text: 'C02.1. ¿Por qué medio/s recibió la notificación?',
          type: 'multiple',
          options: MEDIOS_NOTIFICACION,
          showIf: eq('q28-preparacion', '1'),
          required: true,
        },
        {
          id: 'q28a-medio-otro',
          codigoOriginal: 'C02.1-otro',
          text: 'C02.1. ¿Cuál otro medio?',
          type: 'text',
          showIf: eq('q28a-medio', '97'),
          required: true,
        },
        {
          id: 'q28b-foto-medio',
          codigoOriginal: 'C02.2',
          text: 'C02.2. Adjunte una captura del mensaje de preparación del pedido.',
          type: 'evidence',
          showIf: eq('q28-preparacion', '1'),
          required: true,
        },
        {
          id: 'q29-salida',
          codigoOriginal: 'C03',
          text: 'C03. ¿Recibió una notificación indicando que el pedido fue despachado o está en camino?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q29a-medio',
          codigoOriginal: 'C03.1',
          text: 'C03.1. ¿Por qué medio/s recibió la notificación?',
          type: 'multiple',
          options: MEDIOS_NOTIFICACION,
          showIf: eq('q29-salida', '1'),
          required: true,
        },
        {
          id: 'q29a-medio-otro',
          codigoOriginal: 'C03.1-otro',
          text: 'C03.1. ¿Cuál otro medio?',
          type: 'text',
          showIf: eq('q29a-medio', '97'),
          required: true,
        },
        {
          id: 'q29b-foto-medio',
          codigoOriginal: 'C03.2',
          text: 'C03.2. Adjunte una captura del mensaje de despacho o salida del envío.',
          type: 'evidence',
          showIf: eq('q29-salida', '1'),
          required: true,
        },
        {
          id: 'q30-entregado',
          codigoOriginal: 'C04',
          text: 'C04. ¿Recibió una notificación indicando que el producto fue entregado?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q30a-medio',
          codigoOriginal: 'C04.1',
          text: 'C04.1. ¿Por qué medio/s recibió la notificación?',
          type: 'multiple',
          options: MEDIOS_NOTIFICACION,
          showIf: eq('q30-entregado', '1'),
          required: true,
        },
        {
          id: 'q30b-otro-medio',
          codigoOriginal: 'C04.1-otro',
          text: 'C04.1. ¿Cuál otro medio?',
          type: 'text',
          showIf: eq('q30a-medio', '97'),
          required: true,
        },
        {
          id: 'q30c-foto-medio',
          codigoOriginal: 'C04.2',
          text: 'C04.2. Adjunte una captura del mensaje de producto entregado.',
          type: 'evidence',
          showIf: eq('q30-entregado', '1'),
          required: true,
        },
        {
          id: 'q31-adicionales',
          codigoOriginal: 'C05',
          text: 'C05. Además de las notificaciones anteriores, ¿recibió alguna otra comunicación relacionada con esta compra?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q31a-foto-adicionales',
          codigoOriginal: 'C05.1',
          text: 'C05.1. Adjunte una captura de las notificaciones adicionales relacionadas con esta compra.',
          type: 'evidence',
          showIf: eq('q31-adicionales', '1'),
          required: true,
        },
        {
          id: 'q-d00-cambio-fecha',
          codigoOriginal: 'D00',
          text: 'D00. ¿Recibió una notificación informando un cambio en la fecha de entrega?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
          hint: 'NOTIFICACIÓN DE marketplace POR AJUSTE EN FECHA DE ENTREGA',
        },
        {
          id: 'q54-ajuste-fecha',
          codigoOriginal: 'D01',
          // Word dice "HACER SOLO SI D01 = 1" (typo) → interpretar D00 = 1
          text: 'D01. La fecha de promesa ahora recibida ¿es anterior o posterior a la originalmente recibida al momento de comprar?',
          type: 'single',
          options: [
            {
              value: '1',
              label: 'Se adelanta respecto a la fecha originalmente prometida',
            },
            {
              value: '2',
              label: 'Se posterga la fecha originalmente prometida',
            },
          ],
          showIf: eq('q-d00-cambio-fecha', '1'),
          required: true,
        },
        {
          id: 'q54-1-foto-promesa',
          codigoOriginal: 'D01.1',
          text: 'D01.1. Adjunte una captura de la nueva fecha prometida.',
          type: 'evidence',
          showIf: eq('q-d00-cambio-fecha', '1'),
          required: true,
        },
      ],
    },
    {
      id: 'contactos',
      title: 'CONTACTOS',
      description: 'CONTACTO PRODUCTO DEMORADO',
      questions: [
        {
          id: 'q55-1-contactar-vendedor',
          codigoOriginal: 'D02',
          text: 'D02. ¿Es posible contactar al vendedor para realizar consultas?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q55a-facilidad',
          codigoOriginal: 'D03',
          text: 'D03. En una escala de 0 a 10, donde 0 significa “Extremadamente difícil” y 10 “Extremadamente fácil”, ¿qué tan fácil es contactar al vendedor?',
          type: 'scale',
          scaleMin: 0,
          scaleMax: 10,
          scaleMinLabel: 'Extremadamente difícil',
          scaleMaxLabel: 'Extremadamente fácil',
          showIf: eq('q55-1-contactar-vendedor', '1'),
          required: true,
        },
        {
          id: 'q55a-1-motivo',
          codigoOriginal: 'D03.1',
          text: 'D03.1. ¿Cuál dirías que fue el principal motivo por el cual calificaste de ese modo a [INSERTAR MARCA] en relación a la facilidad de contacto?',
          type: 'single',
          options: [
            { value: '1', label: 'Pocas vías de contacto' },
            { value: '2', label: 'Demoras en la respuesta' },
            { value: '3', label: 'Demoras en establecer contacto' },
            { value: '4', label: 'Otros' },
          ],
          showIf: and(
            eq('q55-1-contactar-vendedor', '1'),
            range('q55a-facilidad', 0, 6)
          ),
          required: true,
        },
        {
          id: 'q55a-1-describa',
          codigoOriginal: 'D03.1.1',
          text: 'D03.1.1. ¿Podría dar más detalles sobre la calificación?',
          type: 'text',
          showIf: and(
            eq('q55-1-contactar-vendedor', '1'),
            range('q55a-facilidad', 0, 6)
          ),
          required: true,
        },
        {
          id: 'q55a-2-mejorar',
          codigoOriginal: 'D03.2',
          text: 'D03.2. ¿Qué tendría que mejorar [INSERTAR MARCA] para que lo/la califiques con un 10 en relación a la facilidad de contacto?',
          type: 'single',
          options: [
            { value: '1', label: 'Ampliar cantidad de medios de contacto' },
            { value: '2', label: 'Responder ágilmente a las consultas' },
            {
              value: '3',
              label: 'Rapidez en tiempo real para establecer contacto',
            },
            { value: '4', label: 'Otros' },
          ],
          showIf: and(
            eq('q55-1-contactar-vendedor', '1'),
            range('q55a-facilidad', 7, 8)
          ),
          required: true,
        },
        {
          id: 'q55a-2-describa',
          codigoOriginal: 'D03.2.1',
          text: 'D03.2.1. ¿Qué otra cosa podría mejorar?',
          type: 'text',
          showIf: and(
            eq('q55-1-contactar-vendedor', '1'),
            range('q55a-facilidad', 7, 8)
          ),
          required: true,
        },
        {
          id: 'q55a-3-motivo',
          codigoOriginal: 'D03.3',
          text: 'D03.3. ¿Cuál dirías que fue el principal motivo por el cual calificaste de ese modo a [INSERTAR MARCA] en relación a la facilidad de contacto?',
          type: 'single',
          options: [
            {
              value: '1',
              label: 'Diversidad de medios de contacto por consultas',
            },
            {
              value: '2',
              label: 'Respuesta ágil y adecuada a las consultas realizadas',
            },
            {
              value: '3',
              label: 'Respuesta en tiempo real para establecer contacto',
            },
            { value: '4', label: 'Otros' },
          ],
          showIf: and(
            eq('q55-1-contactar-vendedor', '1'),
            range('q55a-facilidad', 9, 10)
          ),
          required: true,
        },
        {
          id: 'q55a-3-describa',
          codigoOriginal: 'D03.3.1',
          text: 'D03.3.1. ¿Qué otro motivo fue el principal para dar esa calificación?',
          type: 'text',
          showIf: and(
            eq('q55-1-contactar-vendedor', '1'),
            range('q55a-facilidad', 9, 10)
          ),
          required: true,
        },
        {
          id: 'q55b-foto-ruta',
          codigoOriginal: 'D04',
          text: 'D04. Adjunte capturas de la ruta que realiza para llegar al canal de atención al cliente.',
          type: 'evidence',
          showIf: eq('q55-1-contactar-vendedor', '1'),
          required: true,
        },
        {
          id: 'q55c-atencion-online',
          codigoOriginal: 'D05',
          text: 'D05. ¿Hay atención online disponible por chat o teléfono?',
          type: 'single',
          options: SI_NO_NA,
          required: true,
        },
        {
          id: 'q55d-cancelar',
          codigoOriginal: 'D06',
          text: 'D06. ¿Le permiten cancelar el envío demorado mientras está en camino?',
          type: 'single',
          options: SI_NO_NA,
          required: true,
          hint: 'INSTRUCCIÓN AL MYSTERY: Consulte expresamente si es posible cancelar el envío demorado mientras se encuentra en tránsito.',
        },
        {
          id: 'q55h-plazo-cancelar',
          codigoOriginal: 'D06.1',
          text: 'D06.1. ¿En qué plazo puede cancelar el envío demorado mientras está en camino?',
          type: 'text',
          showIf: eq('q55d-cancelar', '1'),
          required: true,
        },
        {
          id: 'q55e-compensacion',
          codigoOriginal: 'D07',
          text: 'D07. Al solicitar una compensación por la demora, ¿se la otorgan desde atención al cliente?',
          type: 'single',
          options: SI_NO_NA,
          required: true,
          hint: 'INSTRUCCIÓN AL MYSTERY: Consulte al marketplace si hay compensación por la demora sufrida.',
        },
        {
          id: 'q55e1-tipo-compensacion',
          codigoOriginal: 'D07.1',
          text: 'D07.1. ¿Qué tipo de compensación le otorgan?',
          type: 'single',
          options: [
            { value: '1', label: 'Devolución del total de su dinero' },
            { value: '2', label: 'Bonificación para compras futuras' },
            { value: '3', label: 'Puntos para beneficios y suscripciones' },
            { value: '4', label: 'Otra ¿Cuál?' },
          ],
          showIf: eq('q55e-compensacion', '1'),
          required: true,
        },
        {
          id: 'q55e1-otra',
          codigoOriginal: 'D07.1-otra',
          text: 'D07.1. Especifique otra compensación',
          type: 'text',
          showIf: eq('q55e1-tipo-compensacion', '4'),
          required: true,
        },
        {
          id: 'q55f-monto',
          codigoOriginal: 'D07.2',
          text: 'D07.2. ¿Cuál es el monto de la compensación?',
          type: 'number',
          showIf: {
            any: [
              eq('q55e1-tipo-compensacion', '1'),
              eq('q55e1-tipo-compensacion', '2'),
            ],
          },
          required: true,
        },
        {
          id: 'q55g-foto-comunicaciones',
          codigoOriginal: 'D08',
          text: 'D08. Adjunte capturas de todas las comunicaciones con atención al cliente.',
          type: 'evidence',
          required: false,
          hint: 'Ejemplos: chats con atención al cliente y correos electrónicos recibidos con información del caso.',
        },
      ],
    },
    evidenciasModule(2),
  ],
};
