import { SurveySection } from '../types';
import {
  MEDIOS_NOTIFICACION,
  SI_NO_COD,
  SI_NO_NA,
  eq,
  evidenciasModule,
  range,
} from './constants';

// Parte 2: notificaciones + contactos
// Textos literales del .docx (fidelidad textual).

export const parte2: SurveySection = {
  id: 'parte-2',
  title: 'Parte 2 — Notificaciones y contactos',
  description: 'Notificaciones del pedido y contacto con atención al cliente.',
  modules: [
    {
      id: 'notificaciones',
      title: 'NOTIFICACIONES',
      questions: [
        {
          id: 'q27-confirmacion',
          codigoOriginal: '27',
          text: '27. ¿Recibió un mensaje de confirmación de pedido después de la compra?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q27a-medio',
          codigoOriginal: '27a',
          text: '27a. ¿Por qué medio lo notificaron?',
          type: 'multiple',
          options: MEDIOS_NOTIFICACION,
          showIf: eq('q27-confirmacion', '1'),
          required: true,
        },
        {
          id: 'q27a-medio-otro',
          codigoOriginal: '27a-otro',
          text: '27a. ¿Cuál otro medio?',
          type: 'text',
          showIf: eq('q27a-medio', '97'),
          required: true,
        },
        {
          id: 'q28-preparacion',
          codigoOriginal: '28',
          text: '28. ¿Recibió un mensaje de preparación del pedido?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q28a-medio',
          codigoOriginal: '28a',
          text: '28a. ¿Por qué medio lo notificaron?',
          type: 'multiple',
          options: MEDIOS_NOTIFICACION,
          showIf: eq('q28-preparacion', '1'),
          required: true,
        },
        {
          id: 'q28a-medio-otro',
          codigoOriginal: '28a-otro',
          text: '28a. ¿Cuál otro medio?',
          type: 'text',
          showIf: eq('q28a-medio', '97'),
          required: true,
        },
        {
          id: 'q29-salida',
          codigoOriginal: '29',
          text: '29. ¿Recibió un mensaje de salida del envío?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q29a-medio',
          codigoOriginal: '29a',
          text: '29a. ¿Por qué medio lo notificaron?',
          type: 'multiple',
          options: MEDIOS_NOTIFICACION,
          showIf: eq('q29-salida', '1'),
          required: true,
        },
        {
          id: 'q29a-medio-otro',
          codigoOriginal: '29a-otro',
          text: '29a. ¿Cuál otro medio?',
          type: 'text',
          showIf: eq('q29a-medio', '97'),
          required: true,
        },
        {
          id: 'q30-entregado',
          codigoOriginal: '30',
          text: '30. ¿Recibió un mensaje de producto entregado?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q30a-medio',
          codigoOriginal: '30a',
          text: '30a. ¿Por qué medio lo notificaron?',
          type: 'multiple',
          options: [
            { value: '1', label: 'Mail/Correo Electrónico' },
            { value: '2', label: 'Whatsapp' },
            { value: '3', label: 'Site/Página Web' },
            { value: '4', label: 'App' },
            { value: '5', label: 'SMS' },
            { value: '97', label: 'Otro ¿Cuál?' },
          ],
          showIf: eq('q30-entregado', '1'),
          required: true,
        },
        {
          id: 'q30b-otro-medio',
          codigoOriginal: '30b',
          text: '30b. ¿Por qué otro medio lo notificaron?',
          type: 'text',
          showIf: eq('q30a-medio', '97'),
          required: true,
        },
        {
          id: 'q31-1-adicionales',
          codigoOriginal: '31.1',
          text: '31.1. Además de los mensajes anteriormente comentados, ¿Recibió notificaciones adicionales por esta compra?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q31a-foto-adicionales',
          codigoOriginal: '31a',
          text: '31a. Adjuntar imagen de las notificaciones adicionales por esta compra.',
          type: 'evidence',
          showIf: eq('q31-1-adicionales', '1'),
          required: false,
        },
        {
          id: 'q31q3-tracking',
          codigoOriginal: '31Q3',
          text: '31Q3. ¿Recibiste tracking real time del proceso de entrega?',
          type: 'single',
          options: [
            { value: '1', label: 'Sí' },
            { value: '2', label: 'No' },
          ],
          required: true,
          hint: 'Debe ser con mapa o tracking de minuto a minuto en formato Real time. No aplica si es solo el paso a paso en formato de puntos/listado. Necesariamente es el seguimiento por mapeo del producto o por tiempo real.',
        },
        {
          id: 'q31q4-recorrido',
          codigoOriginal: '31Q4',
          text: '31Q4. Cargar en FORMATO TEXTO el recorrido de su compra desde la aprobación hasta su entrega.',
          type: 'longtext',
          required: true,
          hint: 'Ejemplo:',
        },
        {
          id: 'q54-ajuste-fecha',
          codigoOriginal: '54',
          text: '54. ¿La fecha de promesa ahora recibida es anterior o posterior a la originalmente recibida al momento de comprar?',
          type: 'single',
          options: [
            {
              value: '1',
              label: 'Se adelanta respecto a la fecha originalmente prometida',
            },
            {
              value: '2',
              label: 'Se postpone la fecha originalmente prometida',
            },
          ],
          required: true,
          hint: 'Notificación de MARKETPLACE por ajuste en Fecha de entrega',
        },
        {
          id: 'q54-1-foto-promesa',
          codigoOriginal: '54.1',
          text: '54.1. Adjuntar foto de la fecha de promesa.',
          type: 'evidence',
          required: false,
        },
      ],
    },
    {
      id: 'contactos',
      title: 'CONTACTOS',
      description: 'Contacto producto demorado',
      questions: [
        {
          id: 'q55-1-contactar-vendedor',
          codigoOriginal: '55.1',
          text: '55.1. ¿Puede contactarse con su vendedor para hacerle preguntas?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q55a-facilidad',
          codigoOriginal: '55a',
          text: '55a. Siendo 0 "Extremadamente difícil" y 10 "Extremadamente fácil" ¿Cómo calificaría la facilidad de contacto?',
          type: 'scale',
          scaleMin: 0,
          scaleMax: 10,
          scaleMinLabel: 'Extremadamente difícil',
          scaleMaxLabel: 'Extremadamente fácil',
          required: true,
        },
        {
          id: 'q55a-1-motivo',
          codigoOriginal: '55a.1',
          text: '55a.1. ¿Cuál dirías que fue el principal motivo por el cual calificaste de ese modo a [INSERTAR MARCA] en relación a la facilidad de contacto?',
          type: 'single',
          options: [
            { value: '1', label: 'Pocas vías de contacto' },
            { value: '2', label: 'Demoras en la respuesta' },
            { value: '3', label: 'Demoras en establecer contacto' },
            { value: '4', label: 'Otros' },
          ],
          showIf: range('q55a-facilidad', 0, 6),
          required: true,
        },
        {
          id: 'q55a-1-describa',
          codigoOriginal: '55a.1-describa',
          text: 'Describa la Calificación.',
          type: 'text',
          showIf: eq('q55a-1-motivo', '4'),
          required: true,
        },
        {
          id: 'q55a-2-mejorar',
          codigoOriginal: '55a.2',
          text: '55a.2. ¿Qué tendría que mejorar [INSERTAR MARCA] para que lo/la califiques con un 10 en relación a la facilidad de contacto?',
          type: 'single',
          options: [
            { value: '1', label: 'Ampliar cantidad de medios de contacto' },
            { value: '2', label: 'Responder ágilmente a las consultas' },
            {
              value: '3',
              label: 'Rapidez en tiempo real para establecer contacto',
            },
            { value: '4', label: 'Otros' },
          ],
          showIf: range('q55a-facilidad', 7, 8),
          required: true,
        },
        {
          id: 'q55a-2-describa',
          codigoOriginal: '55a.2-describa',
          text: 'Que otra cosa podría mejorar.',
          type: 'text',
          showIf: eq('q55a-2-mejorar', '4'),
          required: true,
        },
        {
          id: 'q55a-3-motivo',
          codigoOriginal: '55a.3',
          text: '55a.3. ¿Cuál dirías que fue el principal motivo por el cual calificaste de ese modo a [INSERTAR MARCA] en relación a la facilidad de contacto?',
          type: 'single',
          options: [
            {
              value: '1',
              label: 'Diversidad de medios de contacto por consultas',
            },
            {
              value: '2',
              label: 'Respuesta ágil y adecuada a las consultas realizadas',
            },
            {
              value: '3',
              label: 'Respuesta en tiempo real para establecer contacto',
            },
            { value: '4', label: 'Otros' },
          ],
          showIf: range('q55a-facilidad', 9, 10),
          required: true,
        },
        {
          id: 'q55a-3-describa',
          codigoOriginal: '55a.3-describa',
          text: 'Que otro motivo fue el principal para la calificación.',
          type: 'text',
          showIf: eq('q55a-3-motivo', '4'),
          required: true,
        },
        {
          id: 'q55b-foto-ruta',
          codigoOriginal: '55b',
          text: '55b. Adjunte fotografías de la ruta que sigue para llegar al contacto con atención al cliente.',
          type: 'evidence',
          required: false,
        },
        {
          id: 'q55c-atencion-online',
          codigoOriginal: '55c',
          text: '55c. ¿Hay disponibilidad de atención online (chat, teléfono)?',
          type: 'single',
          options: SI_NO_NA,
          required: true,
        },
        {
          id: 'q55d-cancelar',
          codigoOriginal: '55d',
          text: '55d. ¿Puede cancelar el envío demorado en camino?',
          type: 'single',
          options: SI_NO_NA,
          required: true,
          hint: 'Mystery debe consultar si puede cancelar envío',
        },
        {
          id: 'q55h-plazo-cancelar',
          codigoOriginal: '55h',
          text: '55h. ¿En qué plazo puede cancelar el envío demorado en camino?',
          type: 'text',
          showIf: eq('q55d-cancelar', '1'),
          required: true,
          hint: 'A partir del accionar solicitado en 55d, responder',
        },
        {
          id: 'q55e-compensacion',
          codigoOriginal: '55e',
          text: '55e. ¿Si exige una compensación por la demora, se la otorgan desde Atención al cliente?',
          type: 'single',
          options: SI_NO_NA,
          required: true,
          hint: 'Consultar con MARKETPLACE si hay compensación por la demora sufrida',
        },
        {
          id: 'q55e1-tipo-compensacion',
          codigoOriginal: '55e1',
          text: '55e1. ¿Qué tipo de compensación le otorgan?',
          type: 'single',
          options: [
            { value: '1', label: 'Devolución del total de su dinero' },
            { value: '2', label: 'Bonificación para compras futuras' },
            { value: '3', label: 'Puntos para beneficios y suscripciones' },
            { value: '4', label: 'Otra ¿Cuál?' },
          ],
          showIf: eq('q55e-compensacion', '1'),
          required: true,
        },
        {
          id: 'q55e1-otra',
          codigoOriginal: '55e1-otra',
          text: 'Que otra compensación otorgan.',
          type: 'text',
          showIf: eq('q55e1-tipo-compensacion', '4'),
          required: true,
        },
        {
          id: 'q55f-monto',
          codigoOriginal: '55f',
          text: '55f. ¿De qué monto?',
          type: 'number',
          showIf: {
            any: [
              eq('q55e1-tipo-compensacion', '1'),
              eq('q55e1-tipo-compensacion', '2'),
            ],
          },
          required: true,
          hint: 'Sólo para opciones 1 “Devolución del total de su dinero” o 2 “Bonificación para compras futuras” de 55e1',
        },
        {
          id: 'q55g-foto-comunicaciones',
          codigoOriginal: '55g',
          text: '55g. Adjunte fotografías de todas las comunicaciones con atención al cliente',
          type: 'evidence',
          required: false,
          hint: 'Ejemplo: chats con atención al cliente, mails que le manden con información.',
        },
      ],
    },
    evidenciasModule(2),
  ],
};
