import { SurveySection } from '../types';
import {
  CATEGORIA_OTRO,
  CATEGORIAS,
  CIUDADES,
  COMPETIDORES,
  ENVIADO_POR,
  INVENTARIO,
  LOGISTICA,
  METODOS_ENTREGA,
  MONEDAS,
  PAISES,
  SI_NO_COD,
  VENDIDO_POR,
  eq,
  evidenciasModule,
} from './constants';
import { naturalDaysBetween, usdFrom } from './computed';

// Parte 1 — cuestionario 03.08 (A + B). IDs internos estables.

export const parte1: SurveySection = {
  id: 'parte-1',
  title: 'Parte 1 — Compra y promesas',
  description: 'Datos de la compra, selección del producto y promesas de entrega.',
  modules: [
    {
      id: 'datos-compra',
      title: 'Datos de la compra',
      questions: [
        {
          id: 'f1-pais',
          codigoOriginal: 'Pais',
          text: 'Pais',
          type: 'single',
          options: PAISES,
          required: true,
          hint: 'Precargado al generar el link. Verifique que sea correcto.',
        },
        {
          id: 'q01-fecha-compra',
          codigoOriginal: 'A01',
          text: 'A01. Fecha de compra',
          type: 'date',
          required: true,
        },
        {
          id: 'q02-hora-compra',
          codigoOriginal: 'A02',
          text: 'A02. Hora de compra',
          type: 'time',
          required: true,
          hint: 'Comprar entre las 8 am y las 13 pm',
          minTime: '08:00',
          maxTime: '13:00',
        },
        {
          id: 'q03-producto',
          codigoOriginal: 'A03',
          text: 'A03. ¿Cuál es el producto evaluado?',
          type: 'text',
          required: true,
          hint: 'Ejemplos: “audífonos”, “mouse”, “tostadora”, “licuadora”, etc',
        },
        {
          id: 'q04-titulo-publicacion',
          codigoOriginal: 'A04',
          text: 'A04. Copie el título de la publicación exactamente como aparece en la página de detalle del producto.',
          type: 'text',
          required: true,
        },
        {
          id: 'q05-link-publicacion',
          codigoOriginal: 'A05',
          text: 'A05. Copie el enlace de la publicación (URL).',
          type: 'text',
          required: true,
        },
        {
          id: 'q06-codigo-compra',
          codigoOriginal: 'A06',
          text: 'A06. Indique el código o identificador de la compra.',
          type: 'text',
          required: true,
        },
        {
          id: 'q8-competidor',
          codigoOriginal: 'A07',
          text: 'A07. ¿Qué marketplace evalúa?',
          type: 'single',
          options: COMPETIDORES,
          required: true,
        },
        {
          id: 'q9-codigo-postal',
          codigoOriginal: 'A08',
          text: 'A08. Indique el código postal de la dirección de entrega.',
          type: 'number',
          required: true,
        },
        {
          id: 'q10-ciudad',
          codigoOriginal: 'A09',
          text: 'A09. ¿Cuál es la ciudad de entrega?',
          type: 'single',
          options: CIUDADES,
          required: true,
        },
      ],
    },
    {
      id: 'seleccion-compra',
      title: 'SELECCIÓN / COMPRA DE PRODUCTO',
      questions: [
        {
          id: 'q11-categoria',
          codigoOriginal: 'A10',
          text: 'A10. ¿A qué categoría pertenece el producto evaluado?',
          type: 'single',
          options: CATEGORIAS,
          required: true,
        },
        {
          id: 'q11-categoria-otra',
          codigoOriginal: 'A10-otra',
          text: 'A10. Especifique la categoría',
          type: 'text',
          showIf: eq('q11-categoria', CATEGORIA_OTRO),
          required: true,
        },
        {
          id: 'q12-precio',
          codigoOriginal: 'A11',
          text: 'A11. ¿Cuál es el precio publicado del producto, sin incluir envío ni impuestos?',
          type: 'number',
          required: true,
          hint: 'Escribí el número sin puntos ni comas de miles. Ejemplo: 87000',
        },
        {
          id: 'q12-1-moneda',
          codigoOriginal: 'A11.1',
          text: 'A11.1. ¿En qué moneda está expresado el precio del producto?',
          type: 'single',
          options: MONEDAS,
          required: true,
        },
        {
          id: 'q12a-precio-usd',
          codigoOriginal: 'A11.2',
          text: 'A11.2. Precio del producto en dólares al momento de la compra. VARIABLE AUXILIAR AUTOMÁTICA.',
          type: 'number',
          required: false,
          computed: usdFrom('q12-precio', 'q12-1-moneda'),
        },
        {
          id: 'q12b-precio-a11b',
          codigoOriginal: 'A11.B',
          // Word: "COD 1 (DOLARES)" — typo; en A11.1 el dólar es código 3
          text: 'A11.B Precio del producto en moneda local al momento de la compra.',
          type: 'number',
          required: true,
          showIf: eq('q12-1-moneda', '3'),
          hint: 'Escribí el número sin puntos ni comas de miles. Ejemplo: 87000',
        },
        {
          id: 'q13-enviado-por',
          codigoOriginal: 'A12',
          text: 'A12. ¿Qué empresa figura en la leyenda “Enviado por”?',
          type: 'single',
          options: ENVIADO_POR,
          required: true,
          hint: '*Siempre el Marketplace es quien hace el Envío.\n* No confundir con la Transportadora, por la cual se pregunta más adelante (pregunta "F09 ¿Con qué transportadora se envió el paquete?") y es quien realiza el traslado del paquete hacia su destino (puede ser el mismo marketplace, o bien una empresa tercerizada, o bien no identificarse).\nEsto hace referencia a productos que no son enviados por el mismo marketplace. Sucede sobre todo en Amazon dónde, por ejemplo, dice “Enviado por”',
        },
        // A16 antes de A13: el PROGRAMADOR de A13 filtra por 1P.
        {
          id: 'q16-inventario',
          codigoOriginal: 'A16',
          text: 'A16. ¿Cuál es el tipo de inventario del producto?',
          type: 'single',
          options: INVENTARIO,
          required: true,
          hint: '1P – Cuando la compra se realiza directamente al ecommerce (Ejemplo: Vendido por Amazon a través de Amazon)\n3P – Cuando la compra se realiza a un tercero (Ejemplo: vendido por Samsung dentro de la plataforma)',
        },
        {
          id: 'q14-vendido-por',
          codigoOriginal: 'A13',
          text: 'A13. ¿Qué empresa figura en la leyenda “Vendido por”?',
          type: 'single',
          options: VENDIDO_POR,
          required: true,
          hint: 'Cuando el producto es 3P vendido por un tercero, la etiqueta dice vendido por: esto se ve mas claro en falabella 1P dice vendido por Falabella 3P dice vendido por xxxx',
        },
        {
          id: 'q14-vendido-por-otro',
          codigoOriginal: 'A13-otro',
          text: 'A13. Especifique vendido por',
          type: 'text',
          showIf: eq('q14-vendido-por', 'otro'),
          required: true,
        },
        {
          id: 'q15-logistica',
          codigoOriginal: 'A14',
          text: 'A14. ¿Cuál es el tipo de logística?',
          type: 'single',
          options: LOGISTICA,
          required: true,
          defaultValue: '1',
          hint: 'Player: producto enviado por Marketplace\nSeller: producto enviado por Seller\n* Seleccionar esta opción. El tipo de logística siempre es “Player”. (Siempre el Marketplace es quien hace el Envío).',
        },
        {
          id: 'q15a-logistica-internacional',
          codigoOriginal: 'A15',
          text: 'A15. ¿La logística del producto es internacional (El producto es importado)?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q15b-pais-origen',
          codigoOriginal: 'A15.1',
          text: 'A15.1. ¿De qué país proviene el producto?',
          type: 'text',
          showIf: eq('q15a-logistica-internacional', '1'),
          required: true,
        },
        {
          id: 'q17-imagen-producto',
          codigoOriginal: 'A17',
          text: 'A17. Adjunte una captura de la publicación del producto en el sitio.',
          type: 'evidence',
          required: true,
          hint: 'La captura debe mostrar la pantalla completa e incluir, como mínimo, el título del producto y el precio.',
        },
        {
          id: 'q18a-opciones-envio',
          codigoOriginal: 'A18',
          text: 'A18. ¿Cuántas opciones de envío están disponibles?',
          type: 'number',
          required: true,
        },
        {
          id: 'q18b-foto-opciones',
          codigoOriginal: 'A18.1',
          text: 'A18.1. Adjunte una captura de pantalla de todas las opciones de envío disponibles.',
          type: 'evidence',
          required: true,
        },
        {
          id: 'q18c-metodo-entrega',
          codigoOriginal: 'A19',
          text: 'A19. ¿Qué método de entrega disponible selecciona?',
          type: 'single',
          options: METODOS_ENTREGA,
          required: true,
          hint: 'INSTRUCCIÓN AL MYSTERY: Seleccione siempre la opción de entrega a domicilio más rápida. En compras Prime, seleccione la opción Prime gratuita a domicilio.',
        },
        {
          id: 'q18d-foto-metodo',
          codigoOriginal: 'A19.1',
          text: 'A19.1. Adjunte una captura de pantalla de la opción de envío seleccionada.',
          type: 'evidence',
          required: true,
          hint: 'Asegúrese de que la captura muestre todos los métodos disponibles, la promesa de entrega y el costo asociado a cada uno.',
        },
        {
          id: 'q19-precio-envio',
          codigoOriginal: 'A20',
          text: 'A20. ¿Cuál es el costo del envío? Si es gratuito, ingrese 0.',
          type: 'number',
          required: true,
          hint: 'Escribí el número sin puntos ni comas de miles. Ejemplo: 87000',
        },
        {
          id: 'q19-1-moneda-envio',
          codigoOriginal: 'A20.1',
          text: 'A20.1. ¿En qué moneda está expresado el costo del envío?',
          type: 'single',
          options: MONEDAS,
          required: true,
        },
        {
          id: 'q19-2-precio-envio-usd',
          codigoOriginal: 'A20.2',
          text: 'A20.2. Costo del envío en dólares. VARIABLE AUXILIAR AUTOMÁTICA.',
          type: 'number',
          required: false,
          computed: usdFrom('q19-precio-envio', 'q19-1-moneda-envio'),
        },
        {
          id: 'q19a-precio-impuestos',
          codigoOriginal: 'A21',
          text: 'A21. ¿Cuál es el importe total de impuestos, tasas de importación o aranceles? Si no corresponde ninguno, ingrese 0.',
          type: 'number',
          required: true,
          hint: 'Escribí el número sin puntos ni comas de miles. Ejemplo: 87000',
        },
        {
          id: 'q19a-1-moneda-impuestos',
          codigoOriginal: 'A21.1',
          text: 'A21.1. ¿En qué moneda están expresados los impuestos, tasas o aranceles?',
          type: 'single',
          options: MONEDAS,
          required: true,
        },
        {
          id: 'q19b-impuestos-usd',
          codigoOriginal: 'A21.2',
          text: 'A21.2. Importe de impuestos, tasas o aranceles en dólares. VARIABLE AUXILIAR AUTOMÁTICA.',
          type: 'number',
          required: false,
          computed: usdFrom('q19a-precio-impuestos', 'q19a-1-moneda-impuestos'),
        },
      ],
    },
    {
      id: 'promesas-entrega',
      title: 'PROMESAS DE ENTREGA',
      questions: [
        {
          id: 'q24-como-fecha',
          codigoOriginal: 'B01',
          text: 'B01. ¿Cómo se informa la fecha estimada de entrega?',
          type: 'single',
          options: [
            { value: '1', label: 'En una fecha específica' },
            { value: '2', label: 'Entre un intervalo de fechas' },
          ],
          required: true,
        },
        {
          id: 'q24a-rango-horario',
          codigoOriginal: 'B02',
          text: 'B02. ¿Se informa uno o más rangos horarios de entrega?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q24a1-rangos-horario',
          codigoOriginal: 'B02.1',
          text: 'B02.1. ¿Cuántos rangos horarios se ofrecen?',
          type: 'number',
          showIf: eq('q24a-rango-horario', '1'),
          required: true,
        },
        {
          id: 'q24b-menos-2h',
          codigoOriginal: 'B03',
          text: 'B03. ¿Hay alguna opción con una promesa de entrega inferior a 2 horas?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q24c-elegir-horarios',
          codigoOriginal: 'B04',
          text: 'B04. ¿Es posible elegir entre distintos horarios para recibir la compra a domicilio?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q24c1-preseleccionada',
          codigoOriginal: 'B04.1',
          text: 'B04.1. ¿Hay alguna opción de rango horario preseleccionada?',
          type: 'single',
          options: SI_NO_COD,
          showIf: eq('q24c-elegir-horarios', '1'),
          required: true,
        },
        {
          id: 'q24c2-cual-preseleccionada',
          codigoOriginal: 'B04.2',
          text: 'B04.2. ¿Qué opción está preseleccionada?',
          type: 'text',
          showIf: eq('q24c1-preseleccionada', '1'),
          required: true,
        },
        {
          id: 'q24d-orden-opciones',
          codigoOriginal: 'B05',
          text: 'B05. ¿En qué orden se muestran las opciones de entrega?',
          type: 'single',
          options: [
            { value: '1', label: '+ rápido a + lento' },
            { value: '2', label: '+ lento a + rápido' },
            {
              value: '3',
              label: 'Ningún orden específico o Ninguna de las anteriores',
            },
          ],
          required: true,
        },
        {
          id: 'q24e-foto-horarios',
          codigoOriginal: 'B06',
          text: 'B06. Adjunte una captura de pantalla en la que se vean todas las opciones de entrega, sus fechas u horarios prometidos.',
          type: 'evidence',
          required: true,
        },
        {
          id: 'q25a-fecha-prevista',
          codigoOriginal: 'B07',
          text: 'B07. ¿Cuál es la fecha prevista de entrega?',
          type: 'date',
          showIf: eq('q24-como-fecha', '1'),
          required: true,
          hint: 'Tenga en mente las siguientes referencias:\nDías naturales = Lunes a Domingo\nDías laborables = Lunes a Viernes',
        },
        {
          id: 'q25b-dias-naturales',
          codigoOriginal: 'B07.1',
          text: 'B07.1. ¿Cuántos días naturales hay desde la fecha de compra hasta la fecha prometida de entrega? VARIABLE AUXILIAR AUTOMÁTICA.',
          type: 'number',
          showIf: eq('q24-como-fecha', '1'),
          required: false,
          computed: naturalDaysBetween('q01-fecha-compra', 'q25a-fecha-prevista'),
        },
        {
          id: 'q26a-primera-fecha',
          codigoOriginal: 'B08',
          text: 'B08. ¿Cuál es la primera fecha del intervalo prometido?',
          type: 'date',
          showIf: eq('q24-como-fecha', '2'),
          required: true,
          hint: 'INTRO: Si el sitio estima la entrega dentro de un período de tiempo…\nEjemplo: llega entre cierra "A" ... y cierra "B" - Aquí necesitamos cierra "A".',
        },
        {
          id: 'q26b-segunda-fecha',
          codigoOriginal: 'B09',
          text: 'B09. ¿Cuál es la última fecha del intervalo prometido?',
          type: 'date',
          showIf: eq('q24-como-fecha', '2'),
          required: true,
          hint: 'Ejemplo: llega entre cierra "A" ... y cierra "B" - Aquí necesitamos cierra "B".',
        },
        {
          id: 'q26e-dias-primera',
          codigoOriginal: 'B08.1',
          text: 'B08.1. ¿Cuántos días naturales hay desde la fecha de compra hasta la primera fecha del intervalo prometido? VARIABLE AUXILIAR AUTOMÁTICA.',
          type: 'number',
          showIf: eq('q24-como-fecha', '2'),
          required: false,
          hint: 'Ejemplo: llega entre cierra "A" ... y cierra "B" - Aquí necesitamos días naturales hasta "A".',
          computed: naturalDaysBetween('q01-fecha-compra', 'q26a-primera-fecha'),
        },
        {
          id: 'q26f-dias-segunda',
          codigoOriginal: 'B09.1',
          text: 'B09.1. ¿Cuántos días naturales hay desde la fecha de compra hasta la última fecha del intervalo prometido? VARIABLE AUXILIAR AUTOMÁTICA.',
          type: 'number',
          showIf: eq('q24-como-fecha', '2'),
          required: false,
          hint: 'Ejemplo: llega entre cierra "A" ... y cierra "B" - Aquí necesitamos días naturales hasta "B".',
          computed: naturalDaysBetween('q01-fecha-compra', 'q26b-segunda-fecha'),
        },
      ],
    },
    evidenciasModule(1),
  ],
};
