import { SurveySection } from '../types';
import {
  CATEGORIAS,
  CIUDADES,
  COMPETIDORES,
  ENVIADO_POR,
  INVENTARIO,
  LOGISTICA,
  METODOS_ENTREGA,
  MONEDAS,
  PAISES,
  SI_NO_COD,
  VENDIDO_POR,
  eq,
  evidenciasModule,
} from './constants';
import { naturalDaysBetween, usdFrom } from './computed';

// Parte 1: datos de compra + selección/compra + promesas de entrega
// Textos literales del .docx (fidelidad textual).

export const parte1: SurveySection = {
  id: 'parte-1',
  title: 'Parte 1 — Compra y promesas',
  description: 'Datos de la compra, selección del producto y promesas de entrega.',
  modules: [
    {
      id: 'datos-compra',
      title: 'Datos de la compra',
      questions: [
        {
          id: 'f1-pais',
          codigoOriginal: 'Pais',
          text: 'Pais',
          type: 'single',
          options: PAISES,
          required: true,
          hint: 'Precargado al generar el link. Verifique que sea correcto.',
        },
        {
          id: 'q01-fecha-compra',
          codigoOriginal: '01',
          text: '01. Fecha de compra',
          type: 'date',
          required: true,
        },
        {
          id: 'q02-hora-compra',
          codigoOriginal: '02',
          text: '02. Hora de compra',
          type: 'time',
          required: true,
          hint: 'Comprar entre las 8 am y las 13 pm',
        },
        {
          id: 'q03-producto',
          codigoOriginal: '03',
          text: '03. Producto (Ítem) Evaluado',
          type: 'text',
          required: true,
          hint: 'Ejemplos: “audífonos”, “mouse”, “tostadora”, “licuadora”, etc',
        },
        {
          id: 'q04-titulo-publicacion',
          codigoOriginal: '04',
          text: '04. Título de la publicación (Tal como está en la página de detalle del producto)',
          type: 'text',
          required: true,
        },
        {
          id: 'q05-link-publicacion',
          codigoOriginal: '05',
          text: '05. Link de la publicación (URL)',
          type: 'text',
          required: true,
        },
        {
          id: 'q8-competidor',
          codigoOriginal: '8',
          text: '8. Competidor',
          type: 'single',
          options: COMPETIDORES,
          required: true,
        },
        {
          id: 'q9-codigo-postal',
          codigoOriginal: '9',
          text: '9.  Código Postal de Entrega (CEP)',
          type: 'number',
          required: true,
        },
        {
          id: 'q10-ciudad',
          codigoOriginal: '10',
          text: '10. Ciudad de entrega',
          type: 'single',
          options: CIUDADES,
          required: true,
        },
      ],
    },
    {
      id: 'seleccion-compra',
      title: 'SELECCIÓN / COMPRA DE PRODUCTO',
      questions: [
        {
          id: 'q11-categoria',
          codigoOriginal: '11',
          text: '11. Categoría del Producto (ítem) evaluado',
          type: 'single',
          options: CATEGORIAS,
          required: true,
        },
        {
          id: 'q11-categoria-otra',
          codigoOriginal: '11-otra',
          text: '11. Especifique la categoría',
          type: 'text',
          showIf: eq('q11-categoria', '19'),
          required: true,
        },
        {
          id: 'q12-precio',
          codigoOriginal: '12',
          text: '12.  Precio del producto en el sitio web (Sin considerar precio de envío o impuestos).',
          type: 'number',
          required: true,
        },
        {
          id: 'q12-1-moneda',
          codigoOriginal: '12.1',
          text: '12.1. Moneda del producto en el sitio web.',
          type: 'single',
          options: MONEDAS,
          required: true,
        },
        {
          id: 'q12a-precio-usd',
          codigoOriginal: '12a',
          text: '12a. Precio del producto en dólares al momento de la compra. VARIABLE AUXILIAR AUTÓMATICA.',
          type: 'number',
          required: false,
          computed: usdFrom('q12-precio', 'q12-1-moneda'),
        },
        {
          id: 'q13-enviado-por',
          codigoOriginal: '13',
          text: '13. Enviado por (Fijarse en la leyenda “Enviado por”) *Siempre el Marketplace es quien hace el Envío.',
          type: 'single',
          options: ENVIADO_POR,
          required: true,
          hint: '* No confundir con la Transportadora, por la cual se pregunta más adelante (pregunta "38.Q1.22. ¿Con qué transportadora se envió el paquete?") y es quien realiza el traslado del paquete hacia su destino (puede ser el mismo marketplace, o bien una empresa terciarizada, o bien no identificarse).',
        },
        {
          id: 'q14-vendido-por',
          codigoOriginal: '14',
          text: '14. Vendido por:',
          type: 'single',
          options: VENDIDO_POR,
          required: true,
          hint: '*Envía el marketplace pero Vende otro. Fijarse en la leyenda “Vendido por …”.',
        },
        {
          id: 'q14-vendido-por-otro',
          codigoOriginal: '14-otro',
          text: '14. Especifique vendido por',
          type: 'text',
          showIf: eq('q14-vendido-por', 'otro'),
          required: true,
        },
        {
          id: 'q15-logistica',
          codigoOriginal: '15',
          text: '15. ¿Cuál es el tipo de logística?',
          type: 'single',
          options: LOGISTICA,
          required: true,
          hint: 'Player: producto enviado por Marketplace\nSeller: producto enviado por Seller',
        },
        {
          id: 'q15a-logistica-internacional',
          codigoOriginal: '15a',
          text: '15a. ¿La logística del producto es Internacional (producto importado)?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q15b-pais-origen',
          codigoOriginal: '15b',
          text: '15b. ¿Desde qué país viene el producto?',
          type: 'text',
          showIf: eq('q15a-logistica-internacional', '1'),
          required: true,
        },
        {
          id: 'q15c-imagen-producto',
          codigoOriginal: '15c',
          text: '15c. Imagen del producto en el sitio.',
          type: 'evidence',
          required: false,
          hint: 'Toda la pantalla, +1 de una impresión para capturar todo: Precio + subtítulo del producto',
        },
        {
          id: 'q16-inventario',
          codigoOriginal: '16',
          text: '16. ¿Cuál es el tipo de inventario del producto?',
          type: 'single',
          options: INVENTARIO,
          required: true,
          hint: '1P – Cuando la compra se realiza directamente al E-Commerce (Ejemplo: Vendido por Amazon a través de Amazon)\n3P – Cuando la compra se realiza a un tercero (Ejemplo: vendido por Samsung dentro de la plataforma)',
        },
        {
          id: 'q17b-origen-item',
          codigoOriginal: '17b',
          text: '17b. Origen del ítem',
          type: 'text',
          required: false,
        },
        {
          id: 'q18n-opciones-envio',
          codigoOriginal: '18n',
          text: '18n ¿Cuántas opciones de envío tienen para elegir?',
          type: 'number',
          required: true,
          hint: 'SUMAR FOTO',
        },
        {
          id: 'q18-metodo-entrega',
          codigoOriginal: '18',
          text: '18. ¿Qué método de entrega disponible se seleccionó?',
          type: 'single',
          options: METODOS_ENTREGA,
          required: true,
          hint: 'Ver referencias. Comprar siempre con el método de entrega más rápido a domicilio entre las opciones ofrecidas, salvo en los casos de compras Prime que hay que comprar con el método Prime gratuito a domicilio.',
        },
        {
          id: 'q18a-foto-metodos',
          codigoOriginal: '18a',
          text: '18a. Adjunta la foto de los métodos de entrega',
          type: 'evidence',
          required: false,
          hint: 'Asegurarse que figuren todos los métodos disponibles con las promesas de cada uno y el costo asociado.',
        },
        {
          id: 'q19-precio-envio',
          codigoOriginal: '19',
          text: '19. ¿Cuál es el precio del envío? (Si no hay costo de envío, poner “0”)',
          type: 'number',
          required: true,
        },
        {
          id: 'q19-1-moneda-envio',
          codigoOriginal: '19.1',
          text: '19.1. Moneda del precio del envío.',
          type: 'single',
          options: MONEDAS,
          required: true,
        },
        {
          id: 'q19-2-precio-envio-usd',
          codigoOriginal: '19.2',
          text: '19.2. Precio del envío en dólares. VARIABLE AUXILIAR AUTÓMATICA.',
          type: 'number',
          required: false,
          computed: usdFrom('q19-precio-envio', 'q19-1-moneda-envio'),
        },
        {
          id: 'q19a-precio-impuestos',
          codigoOriginal: '19a',
          text: '19a. ¿Cuál es el precio de los impuestos (tasa de importación/arancel aduanero/etc.)? (Si no hay impuestos, poner “0”)',
          type: 'number',
          required: true,
        },
        {
          id: 'q19a-1-moneda-impuestos',
          codigoOriginal: '19a.1',
          text: '19a.1. Moneda de los impuestos (tasa de importación/arancel aduanero/etc.).',
          type: 'single',
          options: MONEDAS,
          required: true,
        },
        {
          id: 'q19b-impuestos-usd',
          codigoOriginal: '19b',
          text: '19b. Precio de los impuestos en dólares (tasa de importación/arancel aduanero/etc.)? VARIABLE AUXILIAR AUTÓMATICA.',
          type: 'number',
          required: false,
          computed: usdFrom('q19a-precio-impuestos', 'q19a-1-moneda-impuestos'),
        },
      ],
    },
    {
      id: 'promesas-entrega',
      title: 'PROMESAS DE ENTREGA',
      questions: [
        {
          id: 'q24-como-fecha',
          codigoOriginal: '24',
          text: '24. ¿Cómo se informó la fecha de entrega prevista?',
          type: 'single',
          options: [
            { value: '1', label: 'En una fecha específica' },
            { value: '2', label: 'Entre un intervalo de fechas' },
          ],
          required: true,
        },
        {
          id: 'q24-q3-rango-horario',
          codigoOriginal: '24.Q3',
          text: '24.Q3. ¿Informaron un rango horario de entrega?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q24-1-rangos-horario',
          codigoOriginal: '24.1.Q4.22',
          text: '24.1.Q4.22 ¿Cuantos rangos de horario te ofrecieron?',
          type: 'single',
          options: [
            { value: '1', label: 'Uno' },
            { value: '2', label: 'Dos' },
            { value: '3', label: 'Tres' },
            { value: '97', label: 'Más ¿Cuántos?' },
          ],
          showIf: eq('q24-q3-rango-horario', '1'),
          required: true,
        },
        {
          id: 'q24-1-rangos-cuantos',
          codigoOriginal: '24.1.Q1.23',
          text: '24.1.Q1.23 Especificar cuantas',
          type: 'number',
          showIf: eq('q24-1-rangos-horario', '97'),
          required: true,
        },
        {
          id: 'q24-2-menos-2h',
          codigoOriginal: '24.2.Q1.23',
          text: '24.2.Q1.23 ¿Existe una opción con promesa de entrega menor a 2 horas?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q24-3-elegir-horarios',
          codigoOriginal: '24.3.Q1.23',
          text: '24.3.Q1.23 ¿Tienes posibilidad de elegir entre diferentes horarios para recibir la compra a domicilio?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q24-4-orden-opciones',
          codigoOriginal: '24.4.Q1.23',
          text: '24.4.Q1.23 ¿Cuál es el orden de las opciones?',
          type: 'single',
          options: [
            { value: '1', label: '+ rapido a + lento' },
            { value: '2', label: '+ lento a + rápido' },
            {
              value: '3',
              label: 'Ningún orden especifico o Ninguna de las anteriores',
            },
          ],
          required: true,
        },
        {
          id: 'q24-5-foto-horarios',
          codigoOriginal: '24.5',
          text: '24.5. Adjunte fotografía o print de pantalla que se observe los horarios de entrega ofrecidos.',
          type: 'evidence',
          required: false,
        },
        {
          id: 'q24-5-q1-preseleccionada',
          codigoOriginal: '24.5.Q1.23',
          text: '24.5.Q1.23 ¿Alguna opción de rango horario está pre-seleccionada?',
          type: 'single',
          options: SI_NO_COD,
          required: true,
        },
        {
          id: 'q24-5-1-cual-preseleccionada',
          codigoOriginal: '24.5.1.Q1.23',
          text: '24.5.1.Q1.23 ¿Cual opción está preseleccionada?',
          type: 'text',
          showIf: eq('q24-5-q1-preseleccionada', '1'),
          required: true,
        },
        {
          id: 'q25a-fecha-prevista',
          codigoOriginal: '25a',
          text: '25a. ¿Cuál es la fecha de entrega prevista?',
          type: 'date',
          showIf: eq('q24-como-fecha', '1'),
          required: true,
          hint: 'Tenga en mente las siguientes referencias:\nDías naturales = Lunes a Domingo\nDías laborables = Lunes a Viernes',
        },
        {
          id: 'q25c-dias-naturales',
          codigoOriginal: '25c',
          text: '25c. ¿Cuántos días naturales hay desde la fecha de compra hasta la fecha prometida de entrega?',
          type: 'number',
          showIf: eq('q24-como-fecha', '1'),
          required: false,
          computed: naturalDaysBetween('q01-fecha-compra', 'q25a-fecha-prevista'),
        },
        {
          id: 'q26a-primera-fecha',
          codigoOriginal: '26a',
          text: '26a. Si el sitio estima la entrega dentro de un período de tiempo, ¿cuál fue la primera fecha prometida?',
          type: 'date',
          showIf: eq('q24-como-fecha', '2'),
          required: true,
          hint: 'Ejemplo: llega entre cierra "A" ... y cierra "B" - Aquí necesitamos cierra "A".',
        },
        {
          id: 'q26b-segunda-fecha',
          codigoOriginal: '26b',
          text: '26b. Si el sitio estima la entrega dentro de un período de tiempo, ¿cuál fue la segunda fecha prometida?',
          type: 'date',
          showIf: eq('q24-como-fecha', '2'),
          required: true,
          hint: 'Ejemplo: llega entre cierra "A" ... y cierra "B" - Aquí necesitamos cierra "B".',
        },
        {
          id: 'q26e-dias-primera',
          codigoOriginal: '26e',
          text: '26e. Si el sitio estima la entrega dentro de un período de tiempo, ¿Cuántos días naturales hay desde la fecha de compra hasta la primera fecha prometida? VARIABLE AUXILIAR AUTOMATICA. CALCULO CANTIDAD DE DIAS NATURALES',
          type: 'number',
          showIf: eq('q24-como-fecha', '2'),
          required: false,
          hint: 'Ejemplo: llega entre cierra "A" ... y cierra "B" - Aquí necesitamos días naturales hasta "A".',
          computed: naturalDaysBetween('q01-fecha-compra', 'q26a-primera-fecha'),
        },
        {
          id: 'q26f-dias-segunda',
          codigoOriginal: '26f',
          text: '26f. Si el sitio estima la entrega dentro de un período de tiempo, ¿Cuántos días naturales hay desde la fecha de compra hasta la segunda fecha prometida? VARIABLE AUXILIAR AUTOMATICA. CALCULO CANTIDAD DE DIAS NATURALES',
          type: 'number',
          showIf: eq('q24-como-fecha', '2'),
          required: false,
          hint: 'Ejemplo: llega entre cierra "A" ... y cierra "B" - Aquí necesitamos días naturales hasta "B".',
          computed: naturalDaysBetween('q01-fecha-compra', 'q26b-segunda-fecha'),
        },
      ],
    },
    evidenciasModule(1),
  ],
};
